### ISSUE TITLE
Renaming "__expected"s "eval" keyword

### ISSUE THREAD

**Issue by MentalGear** [typpo/promptfoo#10]
I noticed you're using the term "evaluation" where many testing frameworks typically use "assertion".

Personally, I like evaluation better too, however since there's already __expected's use of "eval" (js), I think having different terms would be more appropriate for a clean and intuitive API.

I propose: 
- renaming __expected "eval" keyword to "run", "exec" or my favorite "fnc" indicating an anonymous functions
- The "eval" regex matcher remains in the code for legacy reasons, but the docs only contain the new keyword

If you concur, I can setup a PR.

**Comment by typpo** [comment]
I'm open to this -- I wonder if "js" might be the most useful prefix, because it indicates which language it actually expects?

**Comment by MentalGear** [comment]
Indeed, I find `js` also visually appealing as a prefix. Ideally though it would be best to use something that conveys the most meaning, and I think, since it's a node module, js as language is somewhat implied.

`lambda` would describe that it is an anonymous function - and would fit if the user can't also put in a named function.

Otherwise I think 'fnc' or 'fn' would be the most useful. Maybe even 'jsFnc' (or 'jsFun' 😁) but that might be too long/descriptive.

Let me know what you think is the best term, and I'm happy to add a PR then. 👨‍💻

**Comment by typpo** [comment]
Sounds good!  Let's go with `fn` :grin:
