### ISSUE TITLE
bug: config (yaml) output

### ISSUE THREAD

**Issue by MentalGear** [typpo/promptfoo#19]
Defining
```yaml
output: output.json
```
does not generate a output file on 0.8.3.

**Comment by typpo** [comment]
This key changed to `outputFile` in the yaml config.  Great catch, I think this is not documented adequately.

**Comment by MentalGear** [comment]
If you aren't already on it, I can update the docs.

**Comment by typpo** [comment]
No worries.  All set here: https://www.promptfoo.dev/docs/configuration/guide#config

**Comment by MentalGear** [comment]
I think the cli 's `output` [argument](https://github.com/typpo/promptfoo/blob/cdbf80676e24bc7cdcc3f15a725f2d61c4529631/src/main.ts#LL136C1-L136C1) should then also be changed to `outputPath` for coherent naming.
