### ISSUE TITLE
Mistake in documentation on JS in csv

### ISSUE THREAD

**Issue by Sekky61** [typpo/promptfoo#27]
Docs on [loading csv](https://www.promptfoo.dev/docs/configuration/expected-outputs#load-an-external-tests-file) mentions how to add JS assertions:

```
text,__expected
...
"Goodbye, everyone!","fn:return output.includes('Au revoir');"
```

This, however, crashes with javascript error. Using `"fn:output.includes('Au revoir');"` (omitting `return`) works fine.

I suggest fixing the docs.

**Comment by typpo** [comment]
Done in https://github.com/typpo/promptfoo-docs/commit/e3fa5af2cd00c14e6b8b0d7ba5d89df209c29922, thanks for catching!
