### ISSUE TITLE
ReliableGPT

### ISSUE THREAD

**Issue by akshhack** [typpo/promptfoo#45]
While using promptfoo, the requests can often fail because of OpenAI's flakiness. I recommend us putting in something like 
https://github.com/BerriAI/reliableGPT
to improve reliability of failing requests. 

Please correct me if there is already a provision for retries. Thank you!

**Comment by typpo** [comment]
Thanks for the suggestion!  I've added retries with exponential backoff, which should help reduce some of the "model is overloaded" and similar OpenAI failures.
